### ISSUE TITLE
Cry of Fear Incompatible

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [FWGS/xash3d-fwgs#1231] opened 2023-02-02 14:46 UTC
Before I can go on, the version of Cry of Fear I am using, is the [mod release](https://archive.org/download/half-lifeseriesmods_20191215_1013/Cry%20of%20Fear/Cry%20of%20Fear%201.0.exe), not the Steam version.

I basically copy and pasted the required DLL files into the main XASH 3D FWGS directory, but I am still getting errors to the point that it doesn't run the maps. At some point in the future, would it be possible to make the mod compatible with XASH 3D FWGS? As well as the Steam version? There might be some branches of XASH 3D FWGS that makes it work, as well as the Half-Life Expansion Packs, but I have sadly lost them, and due to how complicated and overly complex the GitHub site searching can be, it's very difficult to find the appropriate branch.

**Comment by Vladislav4KZ** [comment] 2023-02-02 15:08
I reported the same issue (but in Russian): https://github.com/FWGS/xash3d-fwgs/issues/1000

Is Steam version of CoF even working? I didn't test it.

**Comment by TheKingFireS** [comment] 2023-02-02 19:46
> I reported the same issue (but in Russian): #1000
> 
> Is Steam version of CoF even working? I didn't test it.

I tried run COF steam version on older engine build and it didn't work.
I will test it again.

**Comment by a1batross** [comment] 2023-02-02 20:51
CoF Steam has its own engine branch, like SvenCoop.

Don't try to run it on Xash, it will expectedly crash (no pun intended)

**Comment by ToxicHolyGrenade** [comment] 2023-02-03 10:05
I am not sure, because there can be ways to fix those issues, even if its incredibly difficult. Not that I am talking about the methods I had been using, but certain other ways.

**Comment by a1batross** [comment] 2023-02-03 12:09
No, I don't think we will ever support Steam version. Why? For one not so interesting mod?

The original, non Steam version, **will be supported** but then it's just a duplicate of another issue.

**Closed by a1batross** 2023-02-03 12:09 UTC

**Comment by a1batross** [comment] 2023-02-03 12:34
I just noticed that I misread the OP post, and you tested the mod version, not Steam.

Anyway, it's already has been reported earlier.

**Comment by tizianoamarilla1809-debug** [comment] 2026-08-06 21:01
Después de 3 años ya se puede jugar al Xash3d con un Laucher

**Comment by nekonomicon** [comment] 2026-08-06 22:32
@tizianoamarilla1809-debug Unironically, nope.
