### ISSUE TITLE
[bug] Disappearing parts of interface.

### ISSUE THREAD

**Issue by CortexReaver** [FWGS/xash3d-fwgs#1039] opened 2022-09-15 18:23 UTC
Idk how to reproduce it, happens randomly:
![Скриншот 14-09-2022 013849](https://user-images.githubusercontent.com/34350690/190480651-c931ccb3-8adb-42fa-b774-d5f81bb122e2.png)

**Comment by Vladislav4KZ** [comment] 2022-09-15 18:29
Duplicate of: https://github.com/FWGS/xash3d-fwgs/issues/416

**Closed** 2023-04-28 13:38 UTC
