### ISSUE TITLE
Unable to Load .wad Stored Within .pak When Game is Under XASH3D_RODIR Path

### ISSUE THREAD

**Issue by mmillar-bolis** [FWGS/xash3d-fwgs#1698] opened 2024-06-24 04:05 UTC
__OS:__ Windows 10 x64 (21H2)
__CPU:__ Intel Core i7-8700T @ 2.4GHz
__GPU:__ Nvidia GeForce RTX 2060
__Xash Build:__ 7584bbe, fe3644a (win32-amd64)
__Game DLLs:__ [hlsdk-portable/hlfixed \(05c6e89\)](https://github.com/FWGS/hlsdk-portable/tree/hlfixed)

__Issue:__

When running the program with the `XASH3D_RODIR` environment variable set, if `.wad` files are stored in `.pak` files under that read-only path, they are not able to be loaded. If the `.wad` files are stored loosely under the read-only path, they will be loaded without issue.

__Log Example:__

```
[2024:06:23|20:12:01] FS_Rescan( Half-Life )
[2024:06:23|20:12:01] FS_AddGameHierarchy: adding recursive basedir valve
[2024:06:23|20:12:01] Adding pakfile: C:\Users\Generic\Program Files\Games\Half-Life\App\Episodes/valve/pak0.pak (3453 files)
[2024:06:23|20:12:01] Adding pakfile: C:\Users\Generic\Program Files\Games\Half-Life\App\Episodes/valve/pak1.pak (100 files)
[2024:06:23|20:12:01] Adding pakfile: C:\Users\Generic\Program Files\Games\Half-Life\App\Episodes/valve/pak2.pak (293 files)
[2024:06:23|20:12:01] Error: W_Open: couldn't open C:\Users\Generic\Program Files\Games\Half-Life\App\Episodes/valve/pak2.pak/cached.wad: No such file or directory
[2024:06:23|20:12:01] Error: FS_AddWad_Fullpath: unable to load wad "C:\Users\Generic\Program Files\Games\Half-Life\App\Episodes/valve/pak2.pak/cached.wad"
[2024:06:23|20:12:01] Error: W_Open: couldn't open C:\Users\Generic\Program Files\Games\Half-Life\App\Episodes/valve/pak2.pak/decals.wad: No such file or directory
[2024:06:23|20:12:01] Error: FS_AddWad_Fullpath: unable to load wad "C:\Users\Generic\Program Files\Games\Half-Life\App\Episodes/valve/pak2.pak/decals.wad"
[2024:06:23|20:12:01] Error: W_Open: couldn't open C:\Users\Generic\Program Files\Games\Half-Life\App\Episodes/valve/pak2.pak/fonts.wad: No such file or directory
[2024:06:23|20:12:01] Error: FS_AddWad_Fullpath: unable to load wad "C:\Users\Generic\Program Files\Games\Half-Life\App\Episodes/valve/pak2.pak/fonts.wad"
[2024:06:23|20:12:01] Error: W_Open: couldn't open C:\Users\Generic\Program Files\Games\Half-Life\App\Episodes/valve/pak2.pak/gfx.wad: No such file or directory
[2024:06:23|20:12:01] Error: FS_AddWad_Fullpath: unable to load wad "C:\Users\Generic\Program Files\Games\Half-Life\App\Episodes/valve/pak2.pak/gfx.wad"
```

To be clear, `pak2.pak` actually does contain `cached.wad`. In fact, each `.wad` file mentioned in the log is stored in the `.pak` file that the engine reports not being able to read.

[Log demonstrating problem](https://github.com/user-attachments/files/15949287/engine.log)

However, if the `.wad` files are stored loosely in the game directory, even though the program will still complain about not being able to read them from `.pak`s, it will successfully load the loose `.wad` files and continue initialization.

[Log demonstrating work-around](https://github.com/user-attachments/files/15949335/engine.log)

__Note:__

This problem occurs no matter what the current working directory is set to, so long as the game dir is under the `XASH3D_RODIR` path. It appears to affect both older and current builds, so I made a separate issue for it. I hope this is okay to do.

**Comment by a1batross** [comment] 2024-06-27 02:06
Works for me.

**Comment by a1batross** [comment] 2024-06-27 02:11
Disregard that, I managed to reproduce the bug.

**Comment by a1batross** [comment] 2024-06-27 04:33
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/42f6719e8d354328103f8d9ed9f23d2325e95db7

**Closed by a1batross** 2024-06-27 04:33 UTC

**Comment by mmillar-bolis** [comment] 2024-06-27 05:02
Absolutely fantastic! Thank you so much!
