### ISSUE TITLE
[MOD: Cry of Fear] Excedding VGUI_MAX_TEXTURES 1024 limits will cause killing server.

### ISSUE THREAD

**Issue by TheKingFireS** [FWGS/xash3d-fwgs#1924] opened 2024-12-20 19:49 UTC
Anything that used VGUI, best case is hovering cursor on inventory item icon.

Info:
Patch version: 1.55 (1.2 and 1.0 untested)
Xash3D-FWGS: https://github.com/FWGS/xash3d-fwgs/commit/e751092555975c7ec3a65e1da1144ca6a4e6a1b1
OS: Windows 10 x86_64bit
GPU: GTX 1650
Custom renderer: Enabled
Map: Any

**Comment by nekonomicon** [comment] 2024-12-20 20:56
It's knowledge bug, CoF has a big memory leak in inventory code, even 1.6 version.

**Comment by TheKingFireS** [comment] 2024-12-30 01:35
I have stupid idea, make environment variable named `I_WANT_MEMORY_LEAK` that allow unlimited amount of VGUI_MAX_TEXTURES instead of limited 1024.

**Comment by a1batross** [comment] 2024-12-30 02:09
It won't help that much because there is MAX_TEXTURES limit in the engine.

**Comment by a1batross** [comment] 2024-12-30 03:43
Well, I made a dead simple deduplicator by taking MD5 from texture data, and then looking up if any of the textures have the same hash. It helps to avoid hitting MAX_TEXTURES limit in the engine and potentially leaking VRAM.

The problem is that we cannot deduplicate the texture IDs we sent to VGUI. We might reallocate the array until some hard limit, and after that the engine will refuse loading any new VGUI textures, thus avoiding Host_Error, potential crash and also letting Cry of Fear leak memory all it wants.

**Comment by a1batross** [comment] 2024-12-30 04:27
Fixed by https://github.com/FWGS/xash3d-fwgs/commit/80a473a019408d5819a9d705cc59ce566c0d15b6

**Closed by a1batross** 2024-12-30 04:27 UTC
