### ISSUE TITLE
High Resolution Textures Option Missing

### ISSUE THREAD

**Issue by SkyNinja** [FWGS/xash3d-fwgs#315] opened 2021-02-15 03:30 UTC
In my video options menu, there is no option for high resolution textures. Old Xash documentation cites the command "host_allow_materials", but the command is not found in FWGS. In-game, no custom materials display.

**Comment by a1batross** [comment] 2021-02-15 03:34
It was removed in upstream. We plan to revert it but it's not so easy after engine refactoring.

**Comment by palmerj** [comment] 2022-07-07 08:15
Any progress on this?

**Comment by a1batross** [comment] 2022-07-07 09:55
Unfortunately, nobody worked on it since. :(

**Comment by unattendedplayer** [comment] 2022-11-16 14:22
I support this option to come back. It totally renders my work for an HD mod useless.

**Comment by a1batross** [comment] 2023-01-02 01:11
Duplicate of https://github.com/FWGS/xash3d-fwgs/issues/27

**Closed by a1batross** 2023-01-02 01:11 UTC
