### ISSUE TITLE
Xash3D 0.20 Android crash

### ISSUE THREAD

**Issue by mewS1xN1n3** [FWGS/xash3d-fwgs#193] opened 2020-07-09 16:45 UTC
Installing an addon (as example: Xashbox) in Xashdroid will sometimes cause a crash. Also attempting to change a texture of a button, especially custom ones, will cause a crash.

**Comment by a1batross** [comment] 2022-08-08 21:30
Duplicate of https://github.com/FWGS/xash3d-fwgs/issues/93

**Closed by a1batross** 2022-08-08 21:30 UTC
