### ISSUE TITLE
Client does not connect to server after finishing downloads

### ISSUE THREAD

**Issue by Nexytpowa** [FWGS/xash3d-fwgs#1678] opened 2024-05-30 00:12 UTC
I have this odd issue where the client has to reconnect manually to the server 2 to 3 times to be able to play on the server after downloading all the server's custom content, this issue has persisted in both old (2 years old) and newer engine builds (2 month, and latest to this date).

After some debugging, i've noticed in the client that the cls.state value is stuck at ca_validate and does not change, even after typing "begin" or "spawn" in the console, all this despite having no file left in the http queue. cls.signon remains set at 0

I've tried to find where the problem comes from but with no success, hoping someone can come up with a fix, for now i've simply added a code that reconnects the client to the server if the http queue is empty and ca_validate remains stuck after 5 seconds and that seems to work (even tho it has to reconnect 2 to 3 times, just like before).

**Comment by Nexytpowa** [comment] 2024-05-30 12:25
if that's useful i'm using the x64 builds of xash, with the opfor sdk

**Comment by SNMetamorph** [comment] 2024-05-30 20:47
Yeah I was having this bug long time ago too. But I not used FastDL that time, files was being directly downloaded from server, and when they fully downloaded, client just started waiting for something.

**Comment by a1batross** [comment] 2024-05-30 21:22
I fixed a few fragment bugs yesterday that I caught by running a server.

Didn't do anything about HTTP yet, as this bug doesn't reproduce for me yet. Still wanna rework the way HTTP client notifies engine about completed downloads. There are many branches that don't make sense if HTTP client is correctly plugged into this whole resources management code.

**Comment by a1batross** [comment] 2024-06-02 02:21
Closed by https://github.com/FWGS/xash3d-fwgs/commit/3e1209d3a47c83546f01f959f6ec40c3cd50a6d0

If bug still persists, it might be caused by something different than that, so just post a new issue.

**Closed by a1batross** 2024-06-02 02:21 UTC
