### ISSUE TITLE
Game Crashes on Startup (Redminote13, Android 14, HyperOS 1.0.7.0)

### ISSUE THREAD

**Issue by UnaFlor06** [FWGS/xash3d-fwgs#1886] opened 2024-11-20 02:32 UTC
When I try to run the game, it simply doesn't even starts.
[engine.log](https://github.com/user-attachments/files/17823895/engine.log)

**Comment by a1batross** [comment] 2024-11-20 07:38
I've upgraded SDL to 2.30.9, can you check with the latest build?

**Comment by a1batross** [comment] 2024-11-20 07:39
Duplicate of https://github.com/FWGS/xash3d-fwgs/issues/1809

**Closed by a1batross** 2024-11-20 07:39 UTC
Labels: Android
