### ISSUE TITLE
[OSX] No 32-bit SDL2 library found

### ISSUE THREAD

**Issue by MoeMod** [FWGS/xash3d-fwgs#55] opened 2019-07-06 19:02 UTC
<img width="570" alt="image" src="https://user-images.githubusercontent.com/37328384/60759892-e58b6a80-a05e-11e9-8f2c-d88b09e43e8f.png">

Tested with latest binary release and macOS 10.14.2
Where can I get the required 32-bit SDL2? 
I can't build 32-bit SDL2 with current Xcode because i386 arch is deprecated now by Apple.

**Comment by a1batross** [comment] 2019-07-06 19:17
Try to use older version. 2.0.8 is confirmed to have 32-bit support.

**Comment by MoeMod** [comment] 2019-07-06 19:45
Now I can enter mainui with vgui.dylib copied to release/vgui.dylib
However, creating new game results a segment fault 11.
Maybe client and engine loads two or more different SDL2 shared library and their implements are mixed?

**Comment by MoeMod** [comment] 2019-07-06 19:46
In addition, the mouse (trackpad) is not working. Entering configuration->touch->touch options leads to a segment fault too.

**Comment by a1batross** [comment] 2019-07-06 19:54
We have no OSX maintainer for now. :(

>Maybe client and engine loads two or more different SDL2 shared library and their implements are mixed?

This shouldn't happen, but possible. I dunno if OSX have `ldd` utility, but if it does, you can check which libraries are required and how system found it in path.

**Comment by a1batross** [comment] 2019-07-06 20:01
I have no idea why mouse isn't working.

Touch options will crash until touch support will be restored.

**Comment by MoeMod** [comment] 2019-07-07 08:53
maybe 64bit release by default?
It seems that Apple has dropped 32bit support on Catalina

**Comment by nekonomicon** [comment] 2019-07-07 08:55
And how steam works?
Github version of HLSDK has SDL library for OS X anyway.

**Comment by MoeMod** [comment] 2019-07-07 09:11
> And how steam works?
> Github version of HLSDK has SDL library for OS X anyway.

Steam itself and goldsrc is actually 32bit. Maybe the steam client.dylib links to an older SDL2 while xash3d links to a newer one, and then it crashes...

**Comment by MoeMod** [comment] 2019-07-07 09:12
<img width="570" alt="image" src="https://user-images.githubusercontent.com/37328384/60766300-60de3200-a0da-11e9-9a5e-1abda06c0e37.png">

**Comment by a1batross** [comment] 2019-07-07 09:31
Even if Apple drops 32-bit, maybe it's reasonable to switch over to 64-bit. 

I always want to keep engine **compatible** with Steam releases of the game, but... do we have really much of them? Almost everything is reverse-engineered for now. I don't know real state of OSX support in Steam and GoldSrc and how Valve plans to keep it supported. 

If you want, you can sign up as an OSX port maintainer and remove it from list of platforms that needs to be forced to build for i686 rather than amd64.

**Comment by MoeMod** [comment] 2019-07-08 12:44
Maybe waiting for the official x86_64 build? And then make engine compatible again with the newer game libraries.

**Comment by a1batross** [comment] 2019-07-08 13:05
I doubt that they will port GoldSrc to x86_64. Probably dropping support a lot easier.

Yes, GoldSrc had x86_64 port back then, more than 10 years ago, but it built before ASLR became common and even doesn't work at all.

**Comment by a1batross** [comment] 2019-08-10 11:43
We won't support OSX/iOS anymore because of destructive decisions Apple make. 

Yesterday they removed 32-bit and ok, it's was kinda understandable.
Today they will remove OpenGL for no reason.
Tomorrow they will remove possibility of running native code.

Originally, OSX/iOS support was added because it was easy to maintain, but when it rеquires more action from us, I don't think we can support it without a dedicated maintainer for this platforms. 

Platform code will not be removed, so someone can take it and continue support but I will remove OSX/iOS ports from autobuilds, will not provide them in releases, close all rеlated isssues as WONTFIX and finally remove it from list of supported ports.

So, Apple, f*ck you.

**Closed by a1batross** 2019-08-10 11:43 UTC
