### ISSUE TITLE
Move engine code to C99 language standard

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#849] opened 2022-05-09 15:56 UTC
It'll be more suitable for developers, what stop us from doing this?
We need to discuss.

**Comment by SNMetamorph** [comment] 2022-05-09 15:57
@a1batross @mittorn @nekonomicon

**Comment by nekonomicon** [comment] 2022-05-09 16:39
Duplicate of https://github.com/FWGS/xash3d-fwgs/issues/30

Really, Visual Studio didn't have full C99 support, only possible to use C11 with latest version without some features like _Generic and VLA.

Also, IDK about C99 support in watcom compiler for MS-DOS and motogmax only has gcc 3.0 which not fully supports C99.

**Comment by nekonomicon** [comment] 2022-05-09 16:41
Currently, engine has `pstdint.h` to use C99 types and checks for `tgmath.h` to use optimized math functions for floats.

**Comment by JDragan** [comment] 2022-05-09 22:09
Why not C11? Even the linux kernel eventually will be moved to C11
https://www.zdnet.com/article/linus-torvalds-prepares-to-move-the-linux-kernel-to-modern-c/

Whats the point of maintaining old complex code, when you can use that time for improvements and new features?

Also try portting some functions from xash to [Nim](https://nim-lang.org/), you will enjoy coding again :)

**Comment by a1batross** [comment] 2022-05-09 23:27
@JDragan I'm enjoying just programming in C ¯\_(ツ)_/¯

C11 is supported by even less number of compilers and runtimes. Meanwhile, we easily target GCC 3.4.x because it was used on my old Motorola Linux phone.

**Closed** 2023-01-05 21:57 UTC
