### ISSUE TITLE
Bug with blood trail of gore.

### ISSUE THREAD

**Issue by En04ik** [FWGS/xash3d-fwgs#459] opened 2021-05-29 18:08 UTC
I can't explain this so... there is a screenshot https://ibb.co/KGz4pnk

**Comment by En04ik** [comment] 2021-05-29 18:10
This bug only on xash 0.20.1, you can't see that bug if you are playing on xash 0.19.2 or goldsource

**Comment by hiIexistlol** [comment] 2021-06-02 16:00
looks like brutal doom, i never had that issue and i tried it on the newest version
I didn't see it

**Comment by Vladislav4KZ** [comment] 2021-06-02 16:08
> (looks like brutal doom lol) i never had that issue and i tried it on the newest version
> I didn't see it

Because he uses custom models

**Comment by hiIexistlol** [comment] 2021-06-02 16:10
why would he send an issue if he didn't try it with default assets? they look vanilla to me, the blood decals are stretched, maybe this is only for android?

**Comment by Velaron** [comment] 2021-06-02 16:11
it doesn't matter, if a bug can't be reproduced on goldsrc it is a bug that should be fixed

**Comment by hiIexistlol** [comment] 2021-06-02 16:12
yea, just trying to figure out what is the problem

**Comment by a1batross** [comment] 2024-05-01 12:50
Who knows? If this still happens, post a new issue.

**Closed by a1batross** 2024-05-01 12:50 UTC
