### ISSUE TITLE
[bug] Flashlight doesnt work with VBO on some maps.

### ISSUE THREAD

**Issue by CortexReaver** [FWGS/xash3d-fwgs#1037] opened 2022-09-15 18:06 UTC
Mod that I tested with: https://www.runthinkshootlive.com/posts/issues/ (no pun intended). And the map name is "subzone3", doesn't appear on other maps. Has experienced this bug earlier, but thought it was gone for good already.

![flashlight doesnt work with VBO on some maps map subzone 3](https://user-images.githubusercontent.com/34350690/190477745-31613904-ca53-4505-886f-fe6cb0d469f5.png)

**Comment by Vladislav4KZ** [comment] 2022-09-15 18:12
Duplicate of: https://github.com/FWGS/xash3d-fwgs/issues/574

**Comment by a1batross** [comment] 2022-09-15 19:59
VBO is currently not recommended to use. 

Flashlight is horribly broken in this implementation.

**Comment by a1batross** [comment] 2022-12-08 03:52
VBO is now deprecated.

**Comment by a1batross** [comment] 2023-12-19 15:36
Should be fine with vbo-fix merge.

**Closed by a1batross** 2023-12-19 15:36 UTC
