### ISSUE TITLE
My ideas

### ISSUE THREAD

**Issue by Gorilli09** [FWGS/xash3d-fwgs#1411] opened 2023-08-19 15:58 UTC
- WON/Steam version folder detection
- Toggleable HD graphics if you have an HD folder
- PS2 version model support

**Comment by a1batross** [comment] 2023-08-21 07:11
>WON/Steam version folder detection

Cannot be done in cross-platform manner and I don't really want to make engine this in engine. Make custom launchers and custom scripts for this. For example, Flatpak version tries to detect Steam path, if possible.

>Toggleable HD graphics if you have an HD folder

Dupe of https://github.com/FWGS/xash3d-fwgs/issues/1319

>PS2 version model support

You can just download a mod with converted PS2 models.

**Closed by a1batross** 2023-08-21 07:11 UTC

**Comment by nekonomicon** [comment] 2023-08-21 10:01
> PS2 version model support

It may be actually if someone will try to reverse-engineer PS2 version of Half-Life

And AFAIR PS2 models has one small difference:
 - textures in BGRA4444 format.
